apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: test-ns
data:
  init-user-db.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE DATABASE security;
      
      \c security
      CREATE SCHEMA security;
            
    EOSQL
