apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: test-ns
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/postgres"
    type: DirectoryOrCreate
