apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  image: kindest/node:v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f #(https://github.com/kubernetes-sigs/kind/releases/download/v0.20.0/kind-linux-amd64)
  extraMounts:
  - hostPath: ./kind/data/secret/dockerhub-secret.json
    containerPath: /var/lib/kubelet/config.json
  - hostPath: ./kind/pvc
    containerPath: /data
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
  image: kindest/node:v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f
  extraMounts:
  - hostPath: ./kind/pvc
    containerPath: /data
  # - role: worker
  #   image: kindest/node:v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f
